## Merge a PR on "deploy" branch or push to deploy branch to trigger
## CREATE THESE SECRETS
# TOKEN: Bot token, Make one here: https://developer.webex.com/my-apps/new/bot
# HOST: URL of your Isolate, ex https://speedybot-hub.username.workers.dev
# CF_API_TOKEN: API Token available
name: Deploy Branch
on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      HOST: ${{ secrets.HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Run tests (expects handlers.ts in settings/)
        if: "${{ env.SKIP_TESTS != 'yes' }}"
        run: npm test
      - name: Publish to edge network
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_KEY }}
          secrets: |
            BOT_TOKEN
      - name: Register Webhooks (requires both HOST + BOT_TOKEN secrets)
        if: "${{ env.BOT_TOKEN != '' && env.HOST != '' }}"
        run: npm init speedybot webhook create -- -w ${HOST} -t ${BOT_TOKEN}
